"""Helpers for filter value-provider endpoints.

The ``POST /_values/{field}`` routes generated by the filter
modifier accept a small, shared request body and return a
``{"results": [...], "next_cursor": ...}`` envelope.  This module
supplies that request schema and the in-memory paging helper used
by enum providers; free-text providers issue their own SQL and
build the envelope themselves.
"""

from typing import TYPE_CHECKING, Any

from pydantic import BaseModel

if TYPE_CHECKING:
    from collections.abc import Sequence


_DEFAULT_LIMIT = 50
_MAX_LIMIT = 200


class FilterValuesRequest(BaseModel):
    """Body accepted by every ``POST /_values/{field}`` route.

    A single shared shape so the FE can hit any value-provider
    endpoint with the same request type.
    """

    q: str | None = None
    cursor: str | None = None
    limit: int | None = None


def resolved_limit(req_limit: int | None) -> int:
    """Clamp *req_limit* to ``[1, _MAX_LIMIT]`` with a sensible default."""
    if req_limit is None:
        return _DEFAULT_LIMIT

    return max(1, min(req_limit, _MAX_LIMIT))


def resolved_offset(cursor: str | None) -> int:
    """Decode the cursor as a base-10 offset.  Empty/invalid → 0."""
    if not cursor:
        return 0

    try:
        return max(0, int(cursor))

    except ValueError:
        return 0


def paginate_in_memory(
    items: Sequence[Any],
    request: FilterValuesRequest,
) -> dict[str, Any]:
    """Slice *items* per *request* and emit a ``next_cursor``.

    *items* must already be ``q``-filtered and label-formatted as
    serializable dicts; this helper only handles the page boundary
    so callers don't repeat the cursor arithmetic.
    """
    limit = resolved_limit(request.limit)
    start = resolved_offset(request.cursor)
    end = start + limit
    page = list(items[start:end])
    has_more = end < len(items)
    next_cursor = str(end) if has_more else None
    return {"results": page, "next_cursor": next_cursor}


def enum_values(
    enum_class: type,
    request: FilterValuesRequest,
) -> dict[str, Any]:
    """Page through an enum's members, optionally filtered by ``q``.

    Each member becomes a ``{"value": m.value, "label": m.name}``
    dict; if ``request.q`` is set, members are kept when *q* (case-
    insensitive) appears in either the value or the name.
    """
    members: list[dict[str, Any]] = [
        {"value": m.value, "label": m.name} for m in enum_class
    ]

    if request.q:
        q = request.q.lower()
        members = [
            m
            for m in members
            if q in str(m["value"]).lower() or q in str(m["label"]).lower()
        ]

    return paginate_in_memory(members, request)
