"""Runtime helpers for OpenTelemetry-instrumented kiln apps.

This module is imported by the ``telemetry/setup.py`` and
``telemetry/decorators.py`` files generated by
:class:`kiln.operations.telemetry.TelemetryScaffold`.  Generated
apps without telemetry never import this module.

OpenTelemetry is an *optional* runtime dependency of kiln.  Install
it via ``pip install kiln-generator[opentelemetry]``, or directly
from the pinned ``telemetry/requirements.txt`` that the scaffold
emits next to the generated app.  Importing this module without
OTel installed raises :class:`ImportError`.

The decorators here create internal spans named ``{resource}.{op}``
that survive ASGI middleware reordering and carry low-cardinality
``kiln.resource`` / ``kiln.op`` attributes for filtering.  They
compose cleanly with the request span emitted by
:class:`opentelemetry.instrumentation.fastapi.FastAPIInstrumentor`.
"""

from __future__ import annotations

import functools
import os
from typing import TYPE_CHECKING, Any

from opentelemetry import metrics, trace
from opentelemetry.exporter.otlp.proto.http._log_exporter import OTLPLogExporter
from opentelemetry.exporter.otlp.proto.http.metric_exporter import (
    OTLPMetricExporter,
)
from opentelemetry.exporter.otlp.proto.http.trace_exporter import (
    OTLPSpanExporter as HttpSpanExporter,
)
from opentelemetry.sdk._logs import LoggerProvider
from opentelemetry.sdk._logs.export import BatchLogRecordProcessor
from opentelemetry.sdk.metrics import MeterProvider
from opentelemetry.sdk.metrics.export import PeriodicExportingMetricReader
from opentelemetry.sdk.resources import Resource
from opentelemetry.sdk.trace import TracerProvider
from opentelemetry.sdk.trace.export import (
    BatchSpanProcessor,
    ConsoleSpanExporter,
)
from opentelemetry.sdk.trace.sampling import (
    ALWAYS_OFF,
    ALWAYS_ON,
    ParentBased,
    TraceIdRatioBased,
)

if TYPE_CHECKING:
    from collections.abc import Awaitable, Callable, Mapping

# -------------------------------------------------------------------
# Constants -- attribute keys used throughout, kept in one place so
# the docs page can link to them.
# -------------------------------------------------------------------

ATTR_RESOURCE = "kiln.resource"
"""Span attribute carrying the resource name (e.g. ``"article"``)."""
ATTR_OP = "kiln.op"
"""Span attribute carrying the operation name (e.g. ``"get"``)."""

_SCRUB_PLACEHOLDER = "[scrubbed]"
"""Replacement string written in place of credential / session
attributes on the auth router's spans.  A placeholder rather than
the absent attribute so a missing-attribute alert doesn't mask a
real outage."""


# -------------------------------------------------------------------
# Provider builders
# -------------------------------------------------------------------


def _build_resource(
    *,
    service_name: str,
    service_version: str | None,
    environment: str | None,
    extra: Mapping[str, str],
) -> Resource:
    """Build the OTel ``Resource`` shared across signal providers.

    Centralised so traces, metrics, and logs all carry identical
    resource attributes -- otherwise correlation across signals on
    a single service breaks silently.
    """
    attrs: dict[str, str] = {"service.name": service_name}
    if service_version is not None:
        attrs["service.version"] = service_version
    if environment is not None:
        attrs["deployment.environment.name"] = environment
    attrs.update(extra)
    return Resource.create(attrs)


def _build_sampler(name: str, ratio: float | None) -> Any:
    """Translate the schema's sampler name to an SDK sampler.

    Validation already constrained ``name`` to a known string and
    ratio to ``[0.0, 1.0]`` when applicable; this function trusts
    that and is meant to be a thin lookup.
    """
    if name == "always_on":
        return ALWAYS_ON
    if name == "always_off":
        return ALWAYS_OFF
    if name == "parentbased_always_on":
        return ParentBased(ALWAYS_ON)
    if name == "parentbased_always_off":
        return ParentBased(ALWAYS_OFF)
    if name == "traceidratio":
        assert ratio is not None  # noqa: S101 -- guaranteed by config validator
        return TraceIdRatioBased(ratio)
    if name == "parentbased_traceidratio":
        assert ratio is not None  # noqa: S101 -- guaranteed by config validator
        return ParentBased(TraceIdRatioBased(ratio))
    msg = f"Unknown sampler {name!r}"
    raise ValueError(msg)


def _build_span_exporter(
    exporter: str | None,
    endpoint_env: str,
    headers_env: str,
) -> Any | None:
    """Build a span exporter from the schema's selection.

    Returns ``None`` when ``exporter`` is ``"none"`` (caller skips
    the BatchSpanProcessor).  When ``exporter`` is ``"otlp_grpc"``
    the gRPC exporter is imported lazily because its protobuf stack
    is heavier than the HTTP exporter and would otherwise be
    pulled in for every consumer.
    """
    if exporter == "none":
        return None
    if exporter == "console":
        return ConsoleSpanExporter()
    headers = _parse_otlp_headers(os.environ.get(headers_env, ""))
    endpoint = os.environ.get(endpoint_env)
    if exporter == "otlp_grpc":
        # gRPC stays lazy: it pulls a heavy protobuf/grpc stack that
        # the user only needs when they explicitly select this
        # transport.  ``opentelemetry-exporter-otlp-proto-grpc`` is
        # not in the ``[telemetry]`` extra; consumers who want gRPC
        # add it to their own deps.
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import (  # type: ignore[import-not-found]  # noqa: PLC0415
            OTLPSpanExporter as GrpcSpanExporter,
        )

        return GrpcSpanExporter(endpoint=endpoint, headers=headers or None)
    # Default and "otlp_http": HTTP/protobuf transport which has
    # the smallest dependency footprint and works through proxies.
    return HttpSpanExporter(endpoint=endpoint, headers=headers or None)


def _parse_otlp_headers(raw: str) -> dict[str, str]:
    """Parse the standard ``OTEL_EXPORTER_OTLP_HEADERS`` format.

    Format is comma-separated ``key=value`` pairs (per the OTel
    spec).  Whitespace around keys and values is stripped; empty
    pairs are skipped.  Returns ``{}`` for an empty input rather
    than ``None`` so the caller can pass it directly to exporter
    constructors that accept an optional dict.
    """
    out: dict[str, str] = {}
    for pair in raw.split(","):
        if "=" not in pair:
            continue
        key, _, value = pair.partition("=")
        key = key.strip()
        value = value.strip()
        if key:
            out[key] = value
    return out


def build_tracer_provider(
    *,
    service_name: str,
    service_version: str | None = None,
    environment: str | None = None,
    resource_attributes: Mapping[str, str] | None = None,
    sampler: str = "parentbased_always_on",
    sampler_ratio: float | None = None,
    exporter: str | None = None,
    exporter_endpoint_env: str = "OTEL_EXPORTER_OTLP_ENDPOINT",
    exporter_headers_env: str = "OTEL_EXPORTER_OTLP_HEADERS",
) -> TracerProvider:
    """Build and return a configured ``TracerProvider``.

    The caller is responsible for installing it via
    :func:`opentelemetry.trace.set_tracer_provider`.  Splitting
    construction from installation keeps the helper testable
    without touching the global tracer provider.
    """
    resource = _build_resource(
        service_name=service_name,
        service_version=service_version,
        environment=environment,
        extra=resource_attributes or {},
    )
    provider = TracerProvider(
        resource=resource,
        sampler=_build_sampler(sampler, sampler_ratio),
    )
    span_exporter = _build_span_exporter(
        exporter, exporter_endpoint_env, exporter_headers_env
    )
    if span_exporter is not None:
        provider.add_span_processor(BatchSpanProcessor(span_exporter))
    return provider


def build_meter_provider(
    *,
    service_name: str,
    service_version: str | None = None,
    environment: str | None = None,
    resource_attributes: Mapping[str, str] | None = None,
) -> MeterProvider:
    """Build a ``MeterProvider`` reading exporter config from env.

    The metrics exporter is always selected via the standard
    ``OTEL_METRICS_EXPORTER`` env var (default ``otlp``); we don't
    expose a per-config override because metrics deployments
    almost universally pair with the same OTLP endpoint as traces.
    """
    resource = _build_resource(
        service_name=service_name,
        service_version=service_version,
        environment=environment,
        extra=resource_attributes or {},
    )
    reader = PeriodicExportingMetricReader(OTLPMetricExporter())
    return MeterProvider(resource=resource, metric_readers=[reader])


def build_logger_provider(
    *,
    service_name: str,
    service_version: str | None = None,
    environment: str | None = None,
    resource_attributes: Mapping[str, str] | None = None,
) -> LoggerProvider:
    """Build a ``LoggerProvider`` configured via OTLP env vars.

    Off by default in :class:`~kiln.config.schema.TelemetryConfig`;
    only used when the consumer opts in to log export.
    """
    resource = _build_resource(
        service_name=service_name,
        service_version=service_version,
        environment=environment,
        extra=resource_attributes or {},
    )
    provider = LoggerProvider(resource=resource)
    provider.add_log_record_processor(
        BatchLogRecordProcessor(OTLPLogExporter())
    )
    return provider


# -------------------------------------------------------------------
# Decorators
# -------------------------------------------------------------------


def traced_handler(
    span_name: str,
    *,
    resource: str,
    op: str,
    record_exceptions: bool = True,
) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]:
    """Wrap an async route handler in an internal span.

    Args:
        span_name: Span name, conventionally ``f"{resource}.{op}"``.
        resource: Low-cardinality resource label (e.g. ``"article"``)
            attached as :data:`ATTR_RESOURCE`.
        op: Low-cardinality op label (e.g. ``"get"``) attached as
            :data:`ATTR_OP`.
        record_exceptions: When ``True`` (default), exceptions raised
            from the handler set the span status to ERROR and call
            :meth:`Span.record_exception` before re-raising.

    The returned decorator preserves the wrapped function's signature
    so FastAPI's dependency-injection introspection still works.

    """
    tracer = trace.get_tracer("kiln.handler")

    def decorator(
        fn: Callable[..., Awaitable[Any]],
    ) -> Callable[..., Awaitable[Any]]:
        @functools.wraps(fn)
        async def wrapper(*args: Any, **kwargs: Any) -> Any:
            with tracer.start_as_current_span(
                span_name,
                record_exception=record_exceptions,
                set_status_on_exception=record_exceptions,
            ) as span:
                span.set_attribute(ATTR_RESOURCE, resource)
                span.set_attribute(ATTR_OP, op)
                return await fn(*args, **kwargs)

        return wrapper

    return decorator


def traced_action(
    span_name: str,
    *,
    resource: str,
    action: str,
    record_exceptions: bool = True,
) -> Callable[[Callable[..., Awaitable[Any]]], Callable[..., Awaitable[Any]]]:
    """Variant of :func:`traced_handler` for action operations.

    Differs only in attribute naming: emits ``kiln.resource`` and
    ``kiln.action`` instead of ``kiln.op`` so dashboards can filter
    user-defined actions separately from CRUD ops.
    """
    tracer = trace.get_tracer("kiln.handler")

    def decorator(
        fn: Callable[..., Awaitable[Any]],
    ) -> Callable[..., Awaitable[Any]]:
        @functools.wraps(fn)
        async def wrapper(*args: Any, **kwargs: Any) -> Any:
            with tracer.start_as_current_span(
                span_name,
                record_exception=record_exceptions,
                set_status_on_exception=record_exceptions,
            ) as span:
                span.set_attribute(ATTR_RESOURCE, resource)
                span.set_attribute("kiln.action", action)
                return await fn(*args, **kwargs)

        return wrapper

    return decorator


def scrub_current_span_attributes(*keys: str) -> None:
    """Replace named attributes on the current span with a placeholder.

    The auth router wraps its login/logout handlers in a span that
    *would* otherwise carry the credentials request body and the
    session response body once ``capture_request_body`` /
    ``capture_response_body`` are turned on globally.  This helper
    is invoked from inside those handlers to overwrite specific
    attribute keys (set by a future body-capture hook) with
    :data:`_SCRUB_PLACEHOLDER` -- a placeholder rather than removal
    so a "missing http.request.body" alert doesn't mask an outage.

    Independent of the global capture toggles: even if the consumer
    never turns on body capture, the auth router still calls this
    so any third-party span processor that chooses to attach bodies
    sees the scrubbed value.
    """
    span = trace.get_current_span()
    for key in keys:
        span.set_attribute(key, _SCRUB_PLACEHOLDER)


# -------------------------------------------------------------------
# Lifecycle
# -------------------------------------------------------------------


def shutdown_providers() -> None:
    """Flush and shut down the active providers.

    Useful in test teardown and SIGTERM handlers; production
    deployments under uvicorn typically rely on the SDK's atexit
    hook instead.
    """
    tracer_provider = trace.get_tracer_provider()
    shutdown = getattr(tracer_provider, "shutdown", None)
    if callable(shutdown):
        shutdown()

    meter_provider = metrics.get_meter_provider()
    shutdown = getattr(meter_provider, "shutdown", None)
    if callable(shutdown):
        shutdown()
