"""Pydantic schemas for Post.

Generated by kiln — re-run ``kiln generate`` to update.
"""

from __future__ import annotations

from pydantic import BaseModel

# ---------------------------------------------------------------------------
# Response / request schemas
# ---------------------------------------------------------------------------


class PostResource(BaseModel):
    """Resource schema for Post."""

    title: str
    views: int


class PostCreateRequest(BaseModel):
    """Request body for creating a Post."""

    title: str


class PostUpdateRequest(BaseModel):
    """Request body for updating a Post."""

    title: str | None = None
