"""FastAPI JWT token endpoint.

Generated by kiln — re-run ``kiln generate`` to update.

The ``myapp.auth.verify`` function is called to verify
credentials.  It must accept ``(username: str, password: str)`` and
return a ``dict`` (used as the JWT payload) on success, or ``None``
on failure.

Mount this router in your application::

    from auth.router import router as auth_router
    app.include_router(auth_router)
"""

from __future__ import annotations

import datetime
import os

import jwt
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.security import OAuth2PasswordRequestForm

from myapp.auth import verify

router = APIRouter()


@router.post("/auth/token")
def create_token(
    form_data: OAuth2PasswordRequestForm = Depends(),
) -> dict[str, str]:
    """Exchange username/password credentials for a JWT.

    Args:
        form_data: OAuth2 password grant form fields.

    Returns:
        A dict with ``access_token`` and ``token_type`` keys.

    Raises:
        HTTPException: 401 if credentials are invalid.
    """
    payload = verify(
        form_data.username, form_data.password
    )
    if payload is None:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid credentials",
            headers={"WWW-Authenticate": "Bearer"},
        )
    payload.setdefault(
        "exp",
        datetime.datetime.now(tz=datetime.UTC)
        + datetime.timedelta(minutes=30),
    )
    secret = os.environ["JWT_SECRET"]
    token = jwt.encode(payload, secret, algorithm="HS256")
    return {"access_token": token, "token_type": "bearer"}
