"""Scaffold generator for ``kiln init``.

Produces the one-time boilerplate files that do not change when
the config is updated: the SQLAlchemy/pgcraft base, the async
session factory, and the JWT authentication dependency.
"""

from __future__ import annotations

from kiln.generators.base import GeneratedFile


class ScaffoldGenerator:
    """Generates one-time scaffold files for a new kiln project.

    Call :meth:`generate` to produce the boilerplate files.
    These files are written with ``overwrite=False`` so that
    ``kiln init`` never overwrites hand-edited scaffolds.
    """

    def generate(self) -> list[GeneratedFile]:
        """Return all scaffold files.

        Returns:
            List of :class:`~kiln.generators.base.GeneratedFile`
            objects, all with ``overwrite=False``.

        """
        return [
            GeneratedFile("auth/__init__.py", "", overwrite=False),
            GeneratedFile(
                "auth/dependencies.py",
                _AUTH_DEPS,
                overwrite=False,
            ),
            GeneratedFile("db/__init__.py", "", overwrite=False),
            GeneratedFile("db/base.py", _DB_BASE, overwrite=False),
            GeneratedFile("db/session.py", _DB_SESSION, overwrite=False),
        ]


_AUTH_DEPS = '''\
"""FastAPI JWT authentication dependency.

Generated by ``kiln init``.  Modify as needed.

The secret is read from the environment variable named in
``JWT_SECRET`` (or whatever ``AuthConfig.secret_env`` is set to).
"""

from __future__ import annotations

import os
from typing import Annotated

import jwt
from fastapi import Depends, HTTPException, status
from fastapi.security import OAuth2PasswordBearer

oauth2_scheme = OAuth2PasswordBearer(tokenUrl="/auth/token")


async def get_current_user(
    token: Annotated[str, Depends(oauth2_scheme)],
) -> dict:
    """Validate a JWT bearer token and return the decoded payload.

    Args:
        token: Bearer token extracted by FastAPI's security scheme.

    Returns:
        Decoded JWT payload as a plain dict.

    Raises:
        HTTPException: 401 if the token is invalid or the secret
            env var is not set.
    """
    try:
        secret = os.environ["JWT_SECRET"]
        return jwt.decode(token, secret, algorithms=["HS256"])
    except (jwt.InvalidTokenError, KeyError) as exc:
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Could not validate credentials",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc
'''

_DB_BASE = '''\
"""SQLAlchemy / pgcraft declarative base.

Generated by ``kiln init``.  Modify as needed.

All pgcraft model classes must inherit from ``Base``.
``Base.metadata`` is shared with pgcraft so that Alembic sees
every table, view, and function in one place.
"""

from __future__ import annotations

from pgcraft import PGCraftBase


class Base(PGCraftBase):
    """Project-level base for all pgcraft models and views."""
'''

_DB_SESSION = '''\
"""Async SQLAlchemy session factory.

Generated by ``kiln init``.  Modify as needed.

The database URL is read from the ``DATABASE_URL`` environment
variable at startup.
"""

from __future__ import annotations

import os
from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

_engine = create_async_engine(
    os.environ.get("DATABASE_URL", "postgresql+asyncpg://localhost/dev"),
    echo=False,
)

_SessionLocal = async_sessionmaker(
    _engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def get_db() -> AsyncGenerator[AsyncSession, None]:
    """Yield an async database session.

    Intended for use as a FastAPI dependency::

        DB = Annotated[AsyncSession, Depends(get_db)]
    """
    async with _SessionLocal() as session:
        yield session
'''
