"""Kiln CLI entry point."""

from __future__ import annotations

from pathlib import Path  # noqa: TC003
from typing import TYPE_CHECKING, Annotated

import typer

from kiln.config.loader import load
from kiln.generators.fastapi.views import ViewGenerator
from kiln.generators.init.scaffold import ScaffoldGenerator
from kiln.generators.registry import GeneratorRegistry

if TYPE_CHECKING:
    from kiln.config.schema import KilnConfig
    from kiln.generators.base import GeneratedFile

app = typer.Typer(help="CLI for autogenerating FastAPI + pgcraft files.")


@app.callback()
def main() -> None:
    """CLI for autogenerating files from templates."""


@app.command()
def init(
    out: Annotated[
        Path,
        typer.Option("--out", "-o", help="Output root directory."),
    ],
    config: Annotated[
        Path | None,
        typer.Option(
            "--config",
            "-c",
            help=(
                "Optional path to a .json or .jsonnet project config file. "
                "When provided, per-database session files are generated."
            ),
        ),
    ] = None,
) -> None:
    """Generate one-time scaffold files (db base, session, auth deps).

    Run this once when starting a new project.  Existing files are
    never overwritten.

    Example::

        kiln init --out ./src/app
        kiln init --config project.jsonnet --out ./src/app
    """
    cfg: KilnConfig | None = None
    if config is not None:
        try:
            cfg = load(config)
        except Exception as exc:
            typer.echo(f"Error loading config: {exc}", err=True)
            raise typer.Exit(1) from exc

    scaffold = ScaffoldGenerator()
    files = scaffold.generate(cfg)
    _write_files(files, out)
    typer.echo(f"Scaffold written to {out}")


@app.command()
def generate(
    config: Annotated[
        Path,
        typer.Option(
            "--config",
            "-c",
            help="Path to .json or .jsonnet config file.",
        ),
    ],
    out: Annotated[
        Path,
        typer.Option("--out", "-o", help="Output root directory."),
    ],
    no_validate: Annotated[  # noqa: FBT002
        bool,
        typer.Option(
            "--no-validate",
            help=(
                "Skip validation that query_fn modules exist on the Python "
                "path.  Useful when generating before the app code is written."
            ),
        ),
    ] = False,
) -> None:
    """Generate pgcraft models and FastAPI routes.

    Re-running is always safe — all generated files are overwritten.
    Write generated output into a dedicated directory (e.g.
    ``_autogenerated/``) to keep it clearly separated from hand-written
    code.

    By default, kiln validates that any ``query_fn`` module referenced in
    the config is importable.  Pass ``--no-validate`` to skip this check
    when generating before the app code exists.

    Example::

        kiln generate --config myapp.jsonnet --out app/_autogenerated
    """
    try:
        cfg: KilnConfig = load(config)
    except Exception as exc:
        typer.echo(f"Error loading config: {exc}", err=True)
        raise typer.Exit(1) from exc

    if no_validate:
        ViewGenerator.skip_validation = True

    try:
        registry = GeneratorRegistry.default()
        files = registry.run(cfg)
    except ValueError as exc:
        typer.echo(f"Error: {exc}", err=True)
        raise typer.Exit(1) from exc
    finally:
        ViewGenerator.skip_validation = False

    written, _skipped = _write_files(files, out)
    typer.echo(f"Generated {written} file(s).")


def _write_files(
    files: list[GeneratedFile],
    out_dir: Path,
) -> tuple[int, int]:
    """Write *files* under *out_dir*, respecting the overwrite flag.

    Args:
        files: Files to write.
        out_dir: Root directory for output paths.

    Returns:
        ``(written, skipped)`` counts.

    """
    written = 0
    skipped = 0
    for f in files:
        target = out_dir / f.path
        if target.exists() and not f.overwrite:
            skipped += 1
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(f.content)
        written += 1
    return written, skipped
