"""Aggregated FastAPI router.

Generated by kiln — re-run ``kiln generate`` to update.

Mount this in your application::

    from myapp.routes import router
    app.include_router(router)
"""

from __future__ import annotations

from fastapi import APIRouter

from .post import router as post_router

router = APIRouter()
router.include_router(post_router)
