"""FastAPI routes for Post.

Generated by kiln — re-run ``kiln generate`` to update.
"""

from __future__ import annotations

import uuid
from typing import Annotated

from _generated.auth.dependencies import get_current_user
from _generated.db.primary_session import get_primary_db
from _generated.myapp.schemas.post import (
    PostCreateRequest,
    PostResource,
    PostUpdateRequest,
)
from _generated.myapp.serializers.post import to_post_resource
from _generated.utils import assert_rowcount, get_object_from_query_or_404
from fastapi import APIRouter, Depends
from myapp.models import Post
from sqlalchemy import delete, insert, select, update
from sqlalchemy.ext.asyncio import AsyncSession
from starlette import status

router = APIRouter(prefix="/posts", tags=["post"])

# ---------------------------------------------------------------------------
# Routes
# ---------------------------------------------------------------------------


@router.get("/{id}", response_model=PostResource)
async def get_post(
    id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_primary_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
) -> PostResource:
    """Get a Post by id."""
    obj = await get_object_from_query_or_404(
        db,
        select(Post).where(Post.id == id),
        detail="Post not found",
    )
    return to_post_resource(obj)



@router.get("/", response_model=list[PostResource])
async def list_post(
    db: Annotated[AsyncSession, Depends(get_primary_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
) -> list[PostResource]:
    """List Post records."""
    stmt = select(Post)
    result = await db.execute(stmt)
    return [to_post_resource(obj) for obj in result.scalars()]



@router.post(
    "/",
    status_code=status.HTTP_201_CREATED,
)
async def create_post(
    body: PostCreateRequest,
    db: Annotated[AsyncSession, Depends(get_primary_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
) -> None:
    """Create a Post."""
    await db.execute(insert(Post).values(**body.model_dump()))
    await db.commit()



@router.patch("/{id}")
async def update_post(
    id: uuid.UUID,
    body: PostUpdateRequest,
    db: Annotated[AsyncSession, Depends(get_primary_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
) -> None:
    """Update a Post."""
    result = await db.execute(
        update(Post)
        .where(Post.id == id)
        .values(**body.model_dump(exclude_unset=True))
    )
    assert_rowcount(result, detail="Post not found")
    await db.commit()



@router.delete("/{id}", status_code=status.HTTP_204_NO_CONTENT)
async def delete_post(
    id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_primary_db)],
    current_user: Annotated[dict, Depends(get_current_user)],
) -> None:
    """Delete a Post."""
    result = await db.execute(delete(Post).where(Post.id == id))
    assert_rowcount(result, detail="Post not found")
    await db.commit()
