"""Shared route utilities.

Generated by kiln — re-run ``kiln generate`` to update.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any

from fastapi import HTTPException, status
from pydantic import BaseModel
from sqlalchemy import Select, and_, func, or_
from sqlalchemy.ext.asyncio import AsyncSession

#: Mapping from operator name to SQLAlchemy column method.
#: Used by :func:`apply_filters` to build WHERE clauses from
#: structured filter expressions.
_FILTER_OPS: dict[str, str] = {
    "eq": "__eq__",
    "neq": "__ne__",
    "gt": "__gt__",
    "gte": "__ge__",
    "lt": "__lt__",
    "lte": "__le__",
    "contains": "contains",
    "starts_with": "startswith",
    "in": "in_",
}


def apply_filters(
    stmt: Select,
    node: BaseModel,
    model: type,
) -> Select:
    """Build WHERE clauses from a typed filter expression.

    Accepts a typed Pydantic filter model — either a single
    ``FilterCondition`` (with ``field``, ``op``, ``value``)
    or a ``FilterExpression`` (with ``and_`` / ``or_`` lists
    of nested conditions).

    Field names and operators are validated by the Pydantic
    model's ``Literal`` types before this function is called.

    Args:
        stmt: The SQLAlchemy SELECT statement to filter.
        node: A Pydantic model representing the filter tree.
        model: The SQLAlchemy model class providing columns.

    Returns:
        The statement with WHERE clauses applied.

    """
    clause = _build_filter_clause(node, model)
    if clause is None:
        return stmt
    return stmt.where(clause)


def _build_filter_clause(
    node: BaseModel,
    model: type,
) -> Any:
    """Recursively build a SQLAlchemy clause from a filter node.

    Args:
        node: A Pydantic model representing a filter node.
        model: The SQLAlchemy model class.

    Returns:
        A SQLAlchemy clause element, or ``None`` for empty
        combiner lists.

    """
    and_nodes = getattr(node, "and_", None)
    if and_nodes is not None:
        children = [_build_filter_clause(child, model) for child in and_nodes]
        children = [c for c in children if c is not None]
        if not children:
            return None
        return and_(*children)

    or_nodes = getattr(node, "or_", None)
    if or_nodes is not None:
        children = [_build_filter_clause(child, model) for child in or_nodes]
        children = [c for c in children if c is not None]
        if not children:
            return None
        return or_(*children)

    # Leaf condition
    field_name = getattr(node, "field", None)
    if field_name is None:
        return None

    op = getattr(node, "op", "eq")
    value = getattr(node, "value", None)
    col = getattr(model, field_name)
    op_method = _FILTER_OPS[op]
    return getattr(col, op_method)(value)


def apply_ordering(
    stmt: Select,
    sort_clauses: Sequence[BaseModel] | None,
    model: type,
    default_field: str,
    default_dir: str = "asc",
) -> Select:
    """Apply one or more sort clauses to a SELECT statement.

    Each clause is a Pydantic model with ``field`` (an enum
    whose ``.value`` is the column name) and ``dir``
    (``"asc"`` or ``"desc"``).

    When *sort_clauses* is ``None`` or empty, the default
    field and direction are used.

    Args:
        stmt: The SQLAlchemy SELECT statement to sort.
        sort_clauses: List of sort clause models, or ``None``.
        model: The SQLAlchemy model class providing columns.
        default_field: Column name to sort by when no clauses
            are provided.
        default_dir: Direction for the default sort
            (``"asc"`` or ``"desc"``).

    Returns:
        The statement with ORDER BY applied.

    """
    if not sort_clauses:
        col = getattr(model, default_field)
        if default_dir == "desc":
            return stmt.order_by(col.desc())
        return stmt.order_by(col.asc())

    for clause in sort_clauses:
        col = getattr(model, clause.field.value)
        if clause.dir == "desc":
            stmt = stmt.order_by(col.desc())
        else:
            stmt = stmt.order_by(col.asc())
    return stmt


def apply_keyset_pagination(
    stmt: Select,
    model: type,
    cursor: Any,
    cursor_field: str,
    page_size: int,
    max_page_size: int,
) -> tuple[Select, int]:
    """Apply keyset (cursor-based) pagination to a SELECT.

    Adds a ``WHERE cursor_field > cursor`` clause when a
    cursor is provided, clamps *page_size*, and adds
    ``LIMIT page_size + 1`` (the extra row detects whether
    more results exist).

    Args:
        stmt: The SQLAlchemy SELECT statement.
        model: The SQLAlchemy model class providing columns.
        cursor: The cursor value (already cast to the correct
            type), or ``None``.
        cursor_field: Name of the cursor column.
        page_size: Requested page size.
        max_page_size: Maximum allowed page size.

    Returns:
        ``(modified_stmt, clamped_page_size)`` tuple.

    """
    page_size = min(page_size, max_page_size)
    if cursor is not None:
        col = getattr(model, cursor_field)
        stmt = stmt.where(col > cursor)
    return stmt.limit(page_size + 1), page_size


async def apply_offset_pagination(
    db: AsyncSession,
    stmt: Select,
    offset: int,
    limit: int,
    max_page_size: int,
) -> tuple[int, Sequence[Any]]:
    """Apply offset pagination and execute the query.

    Runs a ``COUNT(*)`` query for the total, then executes the
    statement with ``OFFSET`` / ``LIMIT``.

    Args:
        db: The async database session.
        stmt: The SQLAlchemy SELECT statement (without
            offset/limit applied).
        offset: Number of rows to skip.
        limit: Maximum rows to return.
        max_page_size: Hard ceiling on *limit*.

    Returns:
        ``(total, rows)`` tuple.

    """
    limit = min(limit, max_page_size)
    count_result = await db.execute(stmt.with_only_columns(func.count()))
    total = count_result.scalar_one()
    result = await db.execute(stmt.offset(offset).limit(limit))
    return total, list(result.scalars())


async def get_object_from_query_or_404(
    db: AsyncSession,
    stmt: Any,
    *,
    detail: str = "Not found",
) -> Any:
    """Execute *stmt* and return the first row, or raise HTTP 404.

    Args:
        db: The async database session.
        stmt: A SQLAlchemy selectable statement.
        detail: The error message for the 404 response.

    Returns:
        The first row from the result set.

    Raises:
        HTTPException: With status 404 when no row is found.

    """
    result = await db.execute(stmt)
    row = result.scalars().one_or_none()
    if row is None:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=detail,
        )
    return row


def assert_rowcount(
    result: Any,
    *,
    expected: int = 1,
    status_code: int = status.HTTP_404_NOT_FOUND,
    detail: str = "Not found",
) -> None:
    """Raise HTTPException when *result* did not affect *expected* rows.

    Args:
        result: SQLAlchemy ``CursorResult`` from an ``execute()`` call.
        expected: Number of rows that must have been affected.
        status_code: HTTP status code for the raised exception.
        detail: The error message for the response.

    Raises:
        HTTPException: When ``result.rowcount`` does not equal *expected*.

    """
    if result.rowcount != expected:
        raise HTTPException(status_code=status_code, detail=detail)
