"""Async SQLAlchemy session factory for the 'primary' database.

Generated by ``kiln init``.  Modify as needed.

The database URL is read from the ``DATABASE_URL`` environment
variable at startup.
"""

from __future__ import annotations

import os
from collections.abc import AsyncGenerator

from sqlalchemy.ext.asyncio import (
    AsyncSession,
    async_sessionmaker,
    create_async_engine,
)

_engine = create_async_engine(
    os.environ.get("DATABASE_URL", "postgresql+asyncpg://localhost/dev"),
    echo=False,
    pool_size=5,
    max_overflow=10,
    pool_timeout=30,
    pool_recycle=-1,
    pool_pre_ping=True,
)

_SessionLocal = async_sessionmaker(
    _engine,
    class_=AsyncSession,
    expire_on_commit=False,
)


async def get_primary_db() -> AsyncGenerator[AsyncSession, None]:
    """Yield an async database session.

    Intended for use as a FastAPI dependency::

        DB = Annotated[AsyncSession, Depends(get_primary_db)]
    """
    async with _SessionLocal() as session:
        yield session
