"""Generator that produces FastAPI CRUD route files."""

from __future__ import annotations

from kiln.config.schema import (
    CrudConfig,
    FieldConfig,
    KilnConfig,
    ModelConfig,
)
from kiln.generators._helpers import PYTHON_TYPES
from kiln.generators.base import GeneratedFile

_PK_DEFAULT = FieldConfig(name="id", type="int", primary_key=True)


class CRUDGenerator:
    """Produces a FastAPI router file with CRUD endpoints per model.

    Each generated file contains Pydantic request/response schemas
    and async route handlers that use SQLAlchemy's ORM.  Auth
    dependencies are injected only for operations listed in
    ``crud.require_auth``.

    Generated files are always overwritten on re-generation.
    """

    @property
    def name(self) -> str:
        """Unique generator identifier."""
        return "crud"

    def can_generate(self, config: KilnConfig) -> bool:
        """Return True when any model has a crud config.

        Args:
            config: The validated kiln configuration.
        """
        return any(m.crud is not None for m in config.models)

    def generate(self, config: KilnConfig) -> list[GeneratedFile]:
        """Generate one route file per model that has a crud config.

        Args:
            config: The validated kiln configuration.

        Returns:
            One :class:`~kiln.generators.base.GeneratedFile` per
            qualifying model, written to
            ``api/routes/<name_lower>.py``.
        """
        has_auth = config.auth is not None
        return [
            GeneratedFile(
                path=f"api/routes/{m.name.lower()}.py",
                content=_render_crud(m, m.crud, config.module, has_auth),
            )
            for m in config.models
            if m.crud is not None
        ]


# ---------------------------------------------------------------------------
# Internal rendering helpers
# ---------------------------------------------------------------------------


def _pk(model: ModelConfig) -> FieldConfig:
    """Return the primary-key field, falling back to a synthetic one."""
    return next(
        (f for f in model.fields if f.primary_key),
        _PK_DEFAULT,
    )


def _api_fields(fields: list[FieldConfig]) -> list[FieldConfig]:
    """Fields that appear in the API (not excluded, not internal)."""
    return [f for f in fields if not f.exclude_from_api]


def _create_fields(fields: list[FieldConfig]) -> list[FieldConfig]:
    """Fields that a client supplies when creating a resource."""
    return [
        f
        for f in _api_fields(fields)
        if not f.primary_key
        and not f.auto_now_add
        and not f.auto_now
    ]


def _response_fields(fields: list[FieldConfig]) -> list[FieldConfig]:
    """Fields included in the response model."""
    return _api_fields(fields)


def _py_type(field: FieldConfig) -> str:
    return PYTHON_TYPES[field.type]


def _schema_field_line(field: FieldConfig, *, optional: bool) -> str:
    typ = _py_type(field)
    if optional:
        return f"    {field.name}: {typ} | None = None"
    return f"    {field.name}: {typ}"


def _needs_uuid(fields: list[FieldConfig]) -> bool:
    return any(f.type == "uuid" for f in fields)


def _needs_datetime(fields: list[FieldConfig]) -> bool:
    return any(f.type == "datetime" for f in fields)


def _needs_date(fields: list[FieldConfig]) -> bool:
    return any(f.type == "date" for f in fields)


def _needs_any(fields: list[FieldConfig]) -> bool:
    return any(f.type == "json" for f in fields)


def _render_crud(
    model: ModelConfig,
    crud: CrudConfig,
    module: str,
    has_auth: bool,
) -> str:
    """Render the full CRUD route file for *model*.

    Args:
        model: The model configuration.
        crud: The CRUD settings for this model.
        module: Root module name for generated import paths.
        has_auth: Whether the project has an auth config.

    Returns:
        Python source string.
    """
    pk = _pk(model)
    create_flds = _create_fields(model.fields)
    resp_flds = _response_fields(model.fields)
    all_flds = model.fields

    needs_auth_anywhere = has_auth and bool(crud.require_auth)

    lines: list[str] = [
        f'"""FastAPI CRUD routes for {model.name}.',
        "",
        "Generated by kiln — re-run ``kiln generate`` to update.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]

    # Standard-library imports
    if _needs_uuid(all_flds):
        lines.append("import uuid")
    dt_parts = []
    if _needs_datetime(all_flds):
        dt_parts.append("datetime")
    if _needs_date(all_flds):
        dt_parts.append("date")
    if dt_parts:
        lines.append(f"from datetime import {', '.join(dt_parts)}")
    if _needs_any(all_flds):
        lines.append("from typing import Any")
    lines.append("from typing import Annotated")
    lines.append("")

    # Third-party
    lines.append("from fastapi import APIRouter, Depends, HTTPException, status")
    lines.append("from pydantic import BaseModel")
    lines.append("from sqlalchemy import select")
    lines.append("from sqlalchemy.ext.asyncio import AsyncSession")
    lines.append("")

    # First-party
    if needs_auth_anywhere:
        lines.append(
            f"from {module}.auth.dependencies import get_current_user"
        )
    lines.append(
        f"from {module}.db.models.{model.name.lower()} import {model.name}"
    )
    lines.append(f"from {module}.db.session import get_db")
    lines.append("")

    # Router + type aliases
    lines.append(
        f'router = APIRouter(prefix="/{model.table}", tags=["{model.table}"])'
    )
    lines.append("DB = Annotated[AsyncSession, Depends(get_db)]")
    if needs_auth_anywhere:
        lines.append(
            "CurrentUser = Annotated[dict, Depends(get_current_user)]"
        )
    lines.append("")
    lines.append("")

    # --- Schemas ---
    lines.extend(_create_schema(model, create_flds))
    lines.append("")
    lines.extend(_update_schema(model, create_flds))
    lines.append("")
    lines.extend(_response_schema(model, resp_flds))
    lines.append("")
    lines.append("")

    # --- Routes ---
    if crud.create:
        lines.extend(
            _create_route(model, crud, has_auth)
        )
        lines.append("")
        lines.append("")

    if crud.read:
        lines.extend(_read_route(model, crud, pk, has_auth))
        lines.append("")
        lines.append("")

    if crud.list:
        lines.extend(_list_route(model, crud, has_auth, crud.paginated))
        lines.append("")
        lines.append("")

    if crud.update:
        lines.extend(_update_route(model, crud, pk, has_auth))
        lines.append("")
        lines.append("")

    if crud.delete:
        lines.extend(_delete_route(model, crud, pk, has_auth))
        lines.append("")

    return "\n".join(lines)


def _create_schema(
    model: ModelConfig, fields: list[FieldConfig]
) -> list[str]:
    lines = [
        f"class {model.name}Create(BaseModel):",
        f'    """Request body for creating a {model.name}."""',
        "",
    ]
    if fields:
        lines.extend(_schema_field_line(f, optional=False) for f in fields)
    else:
        lines.append("    pass")
    return lines


def _update_schema(
    model: ModelConfig, fields: list[FieldConfig]
) -> list[str]:
    lines = [
        f"class {model.name}Update(BaseModel):",
        f'    """Request body for partially updating a {model.name}."""',
        "",
    ]
    if fields:
        lines.extend(_schema_field_line(f, optional=True) for f in fields)
    else:
        lines.append("    pass")
    return lines


def _response_schema(
    model: ModelConfig, fields: list[FieldConfig]
) -> list[str]:
    lines = [
        f"class {model.name}Response(BaseModel):",
        f'    """Response model for a {model.name}."""',
        "",
    ]
    for f in fields:
        lines.append(_schema_field_line(f, optional=f.nullable))
    lines.append("")
    lines.append('    model_config = {"from_attributes": True}')
    return lines


def _auth_param(op: str, crud: CrudConfig, *, has_auth: bool) -> str:
    """Return the ``_: CurrentUser,`` line if op requires auth."""
    if has_auth and op in crud.require_auth:
        return "\n    _: CurrentUser,"
    return ""


def _not_found(model: ModelConfig) -> list[str]:
    return [
        "    if instance is None:",
        "        raise HTTPException(",
        "            status_code=status.HTTP_404_NOT_FOUND,",
        f'            detail="{model.name} not found",',
        "        )",
    ]


def _create_route(
    model: ModelConfig, crud: CrudConfig, has_auth: bool
) -> list[str]:
    name = model.name
    lower = name.lower()
    auth = _auth_param("create", crud, has_auth=has_auth)
    return [
        "@router.post(",
        '    "/",',
        f"    response_model={name}Response,",
        "    status_code=status.HTTP_201_CREATED,",
        ")",
        f"async def create_{lower}(",
        f"    body: {name}Create,",
        f"    db: DB,{auth}",
        f") -> {name}:",
        f'    """Create a new {name}."""',
        f"    instance = {name}(**body.model_dump())",
        "    db.add(instance)",
        "    await db.commit()",
        "    await db.refresh(instance)",
        "    return instance",
    ]


def _read_route(
    model: ModelConfig,
    crud: CrudConfig,
    pk: FieldConfig,
    has_auth: bool,
) -> list[str]:
    name = model.name
    lower = name.lower()
    pk_type = PYTHON_TYPES[pk.type]
    auth = _auth_param("read", crud, has_auth=has_auth)
    lines = [
        f'@router.get("/{{{pk.name}}}", response_model={name}Response)',
        f"async def get_{lower}(",
        f"    {pk.name}: {pk_type},",
        f"    db: DB,{auth}",
        f") -> {name}:",
        f'    """Get a {name} by {pk.name}."""',
        "    result = await db.execute(",
        f"        select({name}).where({name}.{pk.name} == {pk.name})",
        "    )",
        "    instance = result.scalars().one_or_none()",
    ]
    lines.extend(_not_found(model))
    lines.append("    return instance")
    return lines


def _list_route(
    model: ModelConfig,
    crud: CrudConfig,
    has_auth: bool,
    paginated: bool,
) -> list[str]:
    name = model.name
    lower = name.lower()
    auth = _auth_param("list", crud, has_auth=has_auth)
    sig = [
        f"    db: DB,{auth}",
    ]
    if paginated:
        sig += ["    offset: int = 0", "    limit: int = 100"]
    body = [
        "    result = await db.execute(",
        f"        select({name})",
    ]
    if paginated:
        body[-1] += ".offset(offset).limit(limit)"
    body.append("    )")
    body.append(f"    return list(result.scalars().all())")
    return [
        f'@router.get("/", response_model=list[{name}Response])',
        f"async def list_{lower}(",
        *sig,
        f") -> list[{name}]:",
        f'    """List {name} records."""',
        *body,
    ]


def _update_route(
    model: ModelConfig,
    crud: CrudConfig,
    pk: FieldConfig,
    has_auth: bool,
) -> list[str]:
    name = model.name
    lower = name.lower()
    pk_type = PYTHON_TYPES[pk.type]
    auth = _auth_param("update", crud, has_auth=has_auth)
    lines = [
        f'@router.patch("/{{{pk.name}}}", response_model={name}Response)',
        f"async def update_{lower}(",
        f"    {pk.name}: {pk_type},",
        f"    body: {name}Update,",
        f"    db: DB,{auth}",
        f") -> {name}:",
        f'    """Update a {name}."""',
        "    result = await db.execute(",
        f"        select({name}).where({name}.{pk.name} == {pk.name})",
        "    )",
        "    instance = result.scalars().one_or_none()",
    ]
    lines.extend(_not_found(model))
    lines += [
        "    for key, value in body.model_dump(exclude_unset=True).items():",
        "        setattr(instance, key, value)",
        "    await db.commit()",
        "    await db.refresh(instance)",
        "    return instance",
    ]
    return lines


def _delete_route(
    model: ModelConfig,
    crud: CrudConfig,
    pk: FieldConfig,
    has_auth: bool,
) -> list[str]:
    name = model.name
    lower = name.lower()
    pk_type = PYTHON_TYPES[pk.type]
    auth = _auth_param("delete", crud, has_auth=has_auth)
    lines = [
        f'@router.delete("/{{{pk.name}}}", status_code=status.HTTP_204_NO_CONTENT)',
        f"async def delete_{lower}(",
        f"    {pk.name}: {pk_type},",
        f"    db: DB,{auth}",
        ") -> None:",
        f'    """Delete a {name}."""',
        "    result = await db.execute(",
        f"        select({name}).where({name}.{pk.name} == {pk.name})",
        "    )",
        "    instance = result.scalars().one_or_none()",
    ]
    lines.extend(_not_found(model))
    lines += [
        "    await db.delete(instance)",
        "    await db.commit()",
    ]
    return lines
