"""Generator that produces pgcraft declarative model files."""

from __future__ import annotations

from kiln.config.schema import FieldConfig, KilnConfig, ModelConfig
from kiln.generators._helpers import PGCRAFT_FACTORIES, column_def
from kiln.generators.base import GeneratedFile


class PGCraftModelGenerator:
    """Produces one pgcraft declarative model file per model in config.

    Each generated file defines a class that inherits from the
    project's ``Base`` (a ``PGCraftBase`` subclass) and carries a
    ``__pgcraft__`` attribute that drives the factory pipeline.

    Generated files are always overwritten on re-generation so that
    column and plugin changes are picked up automatically.
    """

    @property
    def name(self) -> str:
        """Unique generator identifier."""
        return "pgcraft_models"

    def can_generate(self, config: KilnConfig) -> bool:
        """Return True when the config contains at least one model.

        Args:
            config: The validated kiln configuration.
        """
        return bool(config.models)

    def generate(self, config: KilnConfig) -> list[GeneratedFile]:
        """Generate one model file per model in *config*.

        Args:
            config: The validated kiln configuration.

        Returns:
            One :class:`~kiln.generators.base.GeneratedFile` per
            model, written to ``db/models/<name_lower>.py``.
        """
        return [
            GeneratedFile(
                path=f"db/models/{m.name.lower()}.py",
                content=_render_model(m, config.module),
            )
            for m in config.models
        ]


def _needs_uuid(fields: list[FieldConfig]) -> bool:
    return any(f.type == "uuid" for f in fields)


def _needs_datetime(fields: list[FieldConfig]) -> bool:
    return any(f.type == "datetime" for f in fields)


def _needs_date(fields: list[FieldConfig]) -> bool:
    return any(f.type == "date" for f in fields)


def _needs_pg(fields: list[FieldConfig]) -> bool:
    return any(f.type in ("uuid", "datetime", "date", "json") for f in fields)


def _sa_imports(fields: list[FieldConfig]) -> str:
    names = ["Column"]
    if any(f.type in ("str", "email") for f in fields):
        names.append("String")
    if any(f.type == "int" for f in fields):
        names.append("Integer")
    if any(f.type == "float" for f in fields):
        names.append("Float")
    if any(f.type == "bool" for f in fields):
        names.append("Boolean")
    if any(f.auto_now_add or f.auto_now for f in fields):
        names.append("func")
    return f"from sqlalchemy import {', '.join(names)}"


def _render_model(model: ModelConfig, module: str) -> str:
    """Render the full Python source for a pgcraft model class.

    Args:
        model: The model configuration to render.
        module: Root module name for generated import paths.

    Returns:
        Python source string.
    """
    fields = model.fields
    factory_class, factory_module = PGCRAFT_FACTORIES[model.pgcraft_type]
    has_postgrest = "postgrest" in model.pgcraft_plugins
    has_fk = any(f.foreign_key for f in fields)

    lines: list[str] = [
        f'"""pgcraft model for {model.name}.',
        "",
        "Generated by kiln — re-run ``kiln generate`` to update.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]

    # Standard-library imports
    if _needs_uuid(fields):
        lines.append("import uuid")
    dt_parts = []
    if _needs_datetime(fields):
        dt_parts.append("datetime")
    if _needs_date(fields):
        dt_parts.append("date")
    if dt_parts:
        lines.append(f"from datetime import {', '.join(dt_parts)}")
    if dt_parts or _needs_uuid(fields):
        lines.append("")

    # Third-party imports
    lines.append(_sa_imports(fields))
    if _needs_pg(fields):
        lines.append("import sqlalchemy.dialects.postgresql as pg")
    lines.append("")
    if has_fk:
        lines.append("from pgcraft import PGCraftForeignKey")
    lines.append(f"from {factory_module} import {factory_class}")
    if has_postgrest:
        lines.append(
            "from pgcraft.extensions.postgrest import PostgRESTPlugin"
        )
    lines.append("")

    # First-party imports
    lines.append(f"from {module}.db.base import Base")
    lines.append("")
    lines.append("")

    # Class definition
    pgcraft_items = [factory_class]
    if has_postgrest:
        pgcraft_items.append("PostgRESTPlugin()")
    pgcraft_list = ", ".join(pgcraft_items)

    lines.append(f"class {model.name}(Base):")
    lines.append(f'    """pgcraft model for the {model.table} table."""')
    lines.append("")
    lines.append(f'    __tablename__ = "{model.table}"')
    lines.append(f'    __table_args__ = {{"schema": "{model.schema}"}}')
    lines.append(f"    __pgcraft__ = [{pgcraft_list}]")
    lines.append("")

    for field in fields:
        lines.append(f"    {field.name} = {column_def(field)}")

    lines.append("")
    return "\n".join(lines)
