"""Generator that produces the aggregating FastAPI router file."""

from __future__ import annotations

from kiln.config.schema import KilnConfig
from kiln.generators.base import GeneratedFile


class RouterGenerator:
    """Produces ``api/__init__.py`` that mounts every generated router.

    The file imports a router from each CRUD route file and each view
    route file, then combines them into a single ``router`` object
    that the application's ``main.py`` can include::

        from app.api import router
        app.include_router(router)
    """

    @property
    def name(self) -> str:
        """Unique generator identifier."""
        return "router"

    def can_generate(self, config: KilnConfig) -> bool:
        """Return True when there are any routes to aggregate.

        Args:
            config: The validated kiln configuration.
        """
        has_crud = any(m.crud is not None for m in config.models)
        return has_crud or bool(config.views)

    def generate(self, config: KilnConfig) -> list[GeneratedFile]:
        """Generate the aggregating router file.

        Args:
            config: The validated kiln configuration.

        Returns:
            A single :class:`~kiln.generators.base.GeneratedFile`
            at ``api/__init__.py``.
        """
        return [
            GeneratedFile(
                path="api/__init__.py",
                content=_render_router(config),
            )
        ]


def _render_router(config: KilnConfig) -> str:
    """Render the aggregating router source.

    Args:
        config: The validated kiln configuration.

    Returns:
        Python source string.
    """
    lines: list[str] = [
        '"""Aggregated FastAPI router.',
        "",
        "Generated by kiln — re-run ``kiln generate`` to update.",
        "",
        "Mount this in your application::",
        "",
        "    from app.api import router",
        "    app.include_router(router)",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "from fastapi import APIRouter",
        "",
    ]

    crud_models = [m for m in config.models if m.crud is not None]
    imports: list[str] = []
    includes: list[str] = []

    for model in crud_models:
        lower = model.name.lower()
        alias = f"{lower}_router"
        imports.append(
            f"from .routes.{lower} import router as {alias}"
        )
        includes.append(alias)

    for view in config.views:
        alias = f"{view.name}_router"
        imports.append(
            f"from .views.{view.name} import router as {alias}"
        )
        includes.append(alias)

    lines.extend(imports)
    lines.append("")
    lines.append("router = APIRouter()")
    for alias in includes:
        lines.append(f"router.include_router({alias})")
    lines.append("")
    return "\n".join(lines)
