"""Generator for pgcraft view/function stubs and FastAPI view routes.

For each :class:`~kiln.config.schema.ViewModel` in the config two
files are produced:

1. **pgcraft stub** (``db/views/<name>.py``, ``overwrite=False``) —
   a scaffold the developer fills in with the actual SQL query or
   function body.  Non-parameterised views get a
   ``PGCraftViewMixin`` stub; parameterised ones get a
   ``PGCraftFunctionMixin`` stub.

2. **FastAPI route** (``api/views/<name>.py``, ``overwrite=True``) —
   queries the named database object without any inline SQL:

   - Views: ``select(view_table)``
   - Functions: ``func.<schema>.<name>(params).table_valued(cols)``
"""

from __future__ import annotations

from kiln.config.schema import KilnConfig, ViewModel
from kiln.generators._helpers import (
    PG_SQL_TYPES,
    PYTHON_TYPES,
    SA_INSTANCE_TYPES,
)
from kiln.generators.base import GeneratedFile


class ViewGenerator:
    """Generates pgcraft stubs and FastAPI routes for views/functions."""

    @property
    def name(self) -> str:
        """Unique generator identifier."""
        return "views"

    def can_generate(self, config: KilnConfig) -> bool:
        """Return True when the config has at least one view.

        Args:
            config: The validated kiln configuration.
        """
        return bool(config.views)

    def generate(self, config: KilnConfig) -> list[GeneratedFile]:
        """Produce stub and route files for each view in *config*.

        Args:
            config: The validated kiln configuration.

        Returns:
            Two :class:`~kiln.generators.base.GeneratedFile` objects
            per view: a pgcraft stub and a FastAPI route file.
        """
        files: list[GeneratedFile] = []
        for view in config.views:
            files.append(
                GeneratedFile(
                    path=f"db/views/{view.name}.py",
                    content=_render_stub(view, config.module),
                    overwrite=False,
                )
            )
            files.append(
                GeneratedFile(
                    path=f"api/views/{view.name}.py",
                    content=_render_route(view, config.module),
                    overwrite=True,
                )
            )
        return files


# ---------------------------------------------------------------------------
# Stub rendering
# ---------------------------------------------------------------------------


def _render_stub(view: ViewModel, module: str) -> str:
    """Render the pgcraft stub file for *view*.

    Args:
        view: The view configuration.
        module: Root module name for generated import paths.

    Returns:
        Python source string (scaffold, not a complete definition).
    """
    if view.parameters:
        return _render_function_stub(view, module)
    return _render_view_stub(view, module)


def _render_view_stub(view: ViewModel, module: str) -> str:
    """Stub for a non-parameterised pgcraft view."""
    col_lines = "\n".join(
        f"    Column({SA_INSTANCE_TYPES[c.type]}),"
        f"  # {c.name}"
        for c in view.returns
    )
    col_defs = "\n".join(
        f"    Column(\"{c.name}\", {SA_INSTANCE_TYPES[c.type]}),"
        for c in view.returns
    )
    return f'''\
"""pgcraft view stub for {view.name}.

Generated by kiln.  This file will NOT be overwritten on re-generation.

Fill in ``__query__`` with a SQLAlchemy ``select()`` expression that
produces the columns declared below, then run pgcraft migrations.

The ``{view.name}_table`` object at the bottom is a lightweight
SQLAlchemy ``Table`` used by the generated FastAPI route to query
the view — it does not need to change.
"""

from __future__ import annotations

from sqlalchemy import Column, MetaData, Table, func, select  # noqa: F401
import sqlalchemy.dialects.postgresql as pg  # noqa: F401
from pgcraft import PGCraftViewMixin

from {module}.db.base import Base
# from {module}.db.models.<model> import <Model>  # uncomment as needed


# ---------------------------------------------------------------------------
# pgcraft view definition — fill in __query__ before running migrations
# ---------------------------------------------------------------------------

# class {_pascal(view.name)}(PGCraftViewMixin, Base):
#     __tablename__ = "{view.name}"
#     __table_args__ = {{"schema": "{view.schema}"}}
#
#     # Output columns (declare explicitly for accurate ORM mapping)
{_comment_block(col_lines)}
#
#     # TODO: replace with the actual query
#     __query__ = select(
#         ...
#     )


# ---------------------------------------------------------------------------
# SQLAlchemy Table used by the FastAPI route to query this view
# ---------------------------------------------------------------------------

{view.name}_table = Table(
    "{view.name}",
    MetaData(),
{col_defs}
    schema="{view.schema}",
)
'''


def _render_function_stub(view: ViewModel, module: str) -> str:
    """Stub for a parameterised set-returning function."""
    returns_sql = ", ".join(
        f"{c.name} {PG_SQL_TYPES[c.type]}" for c in view.returns
    )
    return f'''\
"""pgcraft function stub for {view.name}.

Generated by kiln.  This file will NOT be overwritten on re-generation.

Fill in the SQL ``definition`` below, then run pgcraft migrations.

The FastAPI route calls this function via SQLAlchemy's
``func.{view.schema}.{view.name}(...).table_valued(...)`` — no SQL
appears in the route file.
"""

from __future__ import annotations

from sqlalchemy_declarative_extensions import register_function
from sqlalchemy_declarative_extensions.dialects.postgresql import Function

from {module}.db.base import Base


# ---------------------------------------------------------------------------
# pgcraft function definition — fill in definition before running migrations
# ---------------------------------------------------------------------------

register_function(
    Base.metadata,
    Function(
        "{view.name}",
        # TODO: replace with the actual SQL body.
        # Parameters are bound positionally: $1, $2, ... in SQL language,
        # or by name in PL/pgSQL.
        """
        -- SELECT ...
        """,
        returns="TABLE({returns_sql})",
        schema="{view.schema}",
        language="sql",
    ),
)
'''


# ---------------------------------------------------------------------------
# Route rendering
# ---------------------------------------------------------------------------


def _render_route(view: ViewModel, module: str) -> str:
    """Render the FastAPI route file for *view*.

    Args:
        view: The view configuration.
        module: Root module name for generated import paths.

    Returns:
        Python source string.
    """
    if view.parameters:
        return _render_function_route(view, module)
    return _render_view_route(view, module)


def _render_view_route(view: ViewModel, module: str) -> str:
    """Route that queries a non-parameterised view via its SA Table."""
    result_class = _pascal(view.name) + "Result"
    has_auth = view.require_auth
    method = view.http_method.lower()
    slug = view.name.replace("_", "-")

    needs_uuid = any(c.type == "uuid" for c in view.returns)
    needs_dt = any(c.type == "datetime" for c in view.returns)
    needs_date = any(c.type == "date" for c in view.returns)
    needs_any = any(c.type == "json" for c in view.returns)

    lines: list[str] = [
        f'"""FastAPI route for the {view.name} view.',
        "",
        "Generated by kiln — re-run ``kiln generate`` to update.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_uuid:
        lines.append("import uuid")
    dt_parts = []
    if needs_dt:
        dt_parts.append("datetime")
    if needs_date:
        dt_parts.append("date")
    if dt_parts:
        lines.append(f"from datetime import {', '.join(dt_parts)}")
    if needs_any:
        lines.append("from typing import Any")
    lines.append("from typing import Annotated")
    lines.append("")
    lines.append("from fastapi import APIRouter, Depends")
    lines.append("from pydantic import BaseModel")
    lines.append("from sqlalchemy import select")
    lines.append("from sqlalchemy.ext.asyncio import AsyncSession")
    lines.append("")
    if has_auth:
        lines.append(
            f"from {module}.auth.dependencies import get_current_user"
        )
    lines.append(f"from {module}.db.session import get_db")
    lines.append(
        f"from {module}.db.views.{view.name} import {view.name}_table"
    )
    lines.append("")
    lines.append(
        f'router = APIRouter(prefix="/{view.name.replace("_", "-")}", '
        f'tags=["{view.name.replace("_", "-")}"])'
    )
    lines.append(
        "DB = Annotated[AsyncSession, Depends(get_db)]"
    )
    if has_auth:
        lines.append(
            "CurrentUser = Annotated[dict, Depends(get_current_user)]"
        )
    lines.append("")
    lines.append("")

    # Response model
    lines.append(f"class {result_class}(BaseModel):")
    lines.append(f'    """Response row from the {view.name} view."""')
    lines.append("")
    for col in view.returns:
        lines.append(f"    {col.name}: {PYTHON_TYPES[col.type]}")
    lines.append("")
    lines.append('    model_config = {"from_attributes": True}')
    lines.append("")
    lines.append("")

    # Route handler
    auth_param = "\n    _: CurrentUser," if has_auth else ""
    desc = view.description or f"Query the {view.name} view."
    lines.append(
        f'@router.{method}("/", response_model=list[{result_class}])'
    )
    lines.append(f"async def get_{view.name}(")
    lines.append(f"    db: DB,{auth_param}")
    lines.append(f") -> list[{result_class}]:")
    lines.append(f'    """{desc}"""')
    lines.append(
        f"    result = await db.execute(select({view.name}_table))"
    )
    lines.append(
        f"    return [{result_class}.model_validate(dict(r._mapping))"
        " for r in result.all()]"
    )
    lines.append("")
    return "\n".join(lines)


def _render_function_route(view: ViewModel, module: str) -> str:
    """Route that calls a set-returning function via func.table_valued."""
    result_class = _pascal(view.name) + "Result"
    has_auth = view.require_auth
    method = view.http_method.lower()

    needs_uuid = any(
        c.type == "uuid" for c in list(view.parameters) + list(view.returns)
    )
    needs_dt = any(
        c.type == "datetime"
        for c in list(view.parameters) + list(view.returns)
    )
    needs_date = any(
        c.type == "date"
        for c in list(view.parameters) + list(view.returns)
    )
    needs_any = any(c.type == "json" for c in view.returns)

    lines: list[str] = [
        f'"""FastAPI route for the {view.name} function.',
        "",
        "Generated by kiln — re-run ``kiln generate`` to update.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
    ]
    if needs_uuid:
        lines.append("import uuid")
    dt_parts = []
    if needs_dt:
        dt_parts.append("datetime")
    if needs_date:
        dt_parts.append("date")
    if dt_parts:
        lines.append(f"from datetime import {', '.join(dt_parts)}")
    if needs_any:
        lines.append("from typing import Any")
    lines.append("from typing import Annotated")
    lines.append("")
    lines.append("from fastapi import APIRouter, Depends")
    lines.append("from pydantic import BaseModel")
    lines.append("from sqlalchemy import column, func, select")
    lines.append("import sqlalchemy.dialects.postgresql as pg")
    lines.append("from sqlalchemy.ext.asyncio import AsyncSession")
    lines.append("")
    if has_auth:
        lines.append(
            f"from {module}.auth.dependencies import get_current_user"
        )
    lines.append(f"from {module}.db.session import get_db")
    lines.append("")
    slug = view.name.replace("_", "-")
    lines.append(
        f'router = APIRouter(prefix="/{slug}", tags=["{slug}"])'
    )
    lines.append("DB = Annotated[AsyncSession, Depends(get_db)]")
    if has_auth:
        lines.append(
            "CurrentUser = Annotated[dict, Depends(get_current_user)]"
        )
    lines.append("")
    lines.append("")

    # Response model
    lines.append(f"class {result_class}(BaseModel):")
    lines.append(
        f'    """Response row from the {view.name} function."""'
    )
    lines.append("")
    for col in view.returns:
        lines.append(f"    {col.name}: {PYTHON_TYPES[col.type]}")
    lines.append("")
    lines.append("")

    # table_valued column specs
    tv_cols = ", ".join(
        f'column("{c.name}", {SA_INSTANCE_TYPES[c.type]})'
        for c in view.returns
    )
    # Function call args (positional, matching parameter order)
    fn_args = ", ".join(p.name for p in view.parameters)

    # Route signature params
    sig_params = [
        f"    {p.name}: {PYTHON_TYPES[p.type]}" for p in view.parameters
    ]
    sig_params.append("    db: DB")
    if has_auth:
        sig_params.append("    _: CurrentUser")

    desc = view.description or f"Call the {view.name} function."
    col_names = ", ".join(f'"{c.name}"' for c in view.returns)

    lines.append(
        f'@router.{method}("/", response_model=list[{result_class}])'
    )
    lines.append(f"async def {view.name}(")
    for p in sig_params:
        lines.append(f"{p},")
    lines.append(f") -> list[{result_class}]:")
    lines.append(f'    """{desc}"""')
    lines.append(f"    fn = func.{view.schema}.{view.name}(")
    lines.append(f"        {fn_args}")
    lines.append(f"    ).table_valued({tv_cols})")
    lines.append("    result = await db.execute(select(fn))")
    lines.append(
        f"    return [{result_class}(**{{k: getattr(row, k)"
        f" for k in [{col_names}]}})"
    )
    lines.append("            for row in result.all()]")
    lines.append("")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _pascal(name: str) -> str:
    """Convert snake_case *name* to PascalCase."""
    return "".join(part.capitalize() for part in name.split("_"))


def _comment_block(text: str) -> str:
    """Prefix each line of *text* with ``# ``."""
    return "\n".join(f"# {line}" if line.strip() else "#" for line in text.splitlines())
