"""Serializers for Post.

Generated by kiln — re-run ``kiln generate`` to update.
"""

from __future__ import annotations

from _generated.myapp.schemas.post import PostListItem, PostResource
from myapp.models import Post


def to_post_resource(obj: Post) -> PostResource:
    """Serialize a Post instance to :class:`PostResource`."""
    return PostResource(
        title=obj.title,
        views=obj.views,
    )

def to_post_list_item(obj: Post) -> PostListItem:
    """Serialize a Post instance to :class:`PostListItem`."""
    return PostListItem(
        title=obj.title,
        views=obj.views,
    )
